var countriesInfo = {
  "countries":[
 {"id_country":"DEU                             ","country":"Germany","flag":"de","bands":416},
 {"id_country":"USA                             ","country":"United States of America","flag":"us","bands":112},
 {"id_country":"SWE                             ","country":"Sweden","flag":"se","bands":48},
 {"id_country":"GBR                             ","country":"United Kingdom of Great Britain and Northern Ireland","flag":"gb","bands":43},
 {"id_country":"NLD                             ","country":"Netherlands","flag":"nl","bands":33},
 {"id_country":"FRA                             ","country":"France","flag":"fr","bands":28},
 {"id_country":"FIN                             ","country":"Finland","flag":"fi","bands":26},
 {"id_country":"ITA                             ","country":"Italy","flag":"it","bands":23},
 {"id_country":"BEL                             ","country":"Belgium","flag":"be","bands":22},
 {"id_country":"AUT                             ","country":"Austria","flag":"at","bands":21},
 {"id_country":"DNK                             ","country":"Denmark","flag":"dk","bands":20},
 {"id_country":"NOR                             ","country":"Norway","flag":"no","bands":17},
 {"id_country":"CHE                             ","country":"Switzerland","flag":"ch","bands":17},
 {"id_country":"CZE                             ","country":"Czechia","flag":"cz","bands":12},
 {"id_country":"AUS                             ","country":"Australia","flag":"au","bands":11},
 {"id_country":"BRA                             ","country":"Brazil","flag":"br","bands":10},
 {"id_country":"POL                             ","country":"Poland","flag":"pl","bands":9},
 {"id_country":"PRT                             ","country":"Portugal","flag":"pt","bands":9},
 {"id_country":"CAN                             ","country":"Canada","flag":"ca","bands":8},
 {"id_country":"GRC                             ","country":"Greece","flag":"gr","bands":8},
 {"id_country":"ESP                             ","country":"Spain","flag":"es","bands":8},
 {"id_country":"ISL                             ","country":"Iceland","flag":"is","bands":6},
 {"id_country":"CHL                             ","country":"Chile","flag":"cl","bands":5},
 {"id_country":"150                             ","country":"Europe","flag":"eu","bands":5},
 {"id_country":"MEX                             ","country":"Mexico","flag":"mx","bands":5},
 {"id_country":"HUN                             ","country":"Hungary","flag":"hu","bands":4},
 {"id_country":"ISR                             ","country":"Israel","flag":"il","bands":4},
 {"id_country":"LUX                             ","country":"Luxembourg","flag":"lu","bands":4},
 {"id_country":"BLR                             ","country":"Belarus","flag":"by","bands":3},
 {"id_country":"CUB                             ","country":"Cuba","flag":"cu","bands":3},
 {"id_country":"001                             ","country":"International","flag":"un","bands":3},
 {"id_country":"MLT                             ","country":"Malta","flag":"mt","bands":3},
 {"id_country":"UKR                             ","country":"Ukraine","flag":"ua","bands":3},
 {"id_country":"CRI                             ","country":"Costa Rica","flag":"cr","bands":2},
 {"id_country":"HRV                             ","country":"Croatia","flag":"hr","bands":2},
 {"id_country":"EST                             ","country":"Estonia","flag":"ee","bands":2},
 {"id_country":"IND                             ","country":"India","flag":"in","bands":2},
 {"id_country":"RUS                             ","country":"Russian Federation","flag":"ru","bands":2},
 {"id_country":"SRB                             ","country":"Serbia","flag":"rs","bands":2},
 {"id_country":"TUR                             ","country":"Türkiye","flag":"tr","bands":2},
 {"id_country":"ARG                             ","country":"Argentina","flag":"ar","bands":1},
 {"id_country":"CHN                             ","country":"China","flag":"cn","bands":1},
 {"id_country":"COL                             ","country":"Colombia","flag":"co","bands":1},
 {"id_country":"EGY                             ","country":"Egypt","flag":"eg","bands":1},
 {"id_country":"FRO                             ","country":"Faroe Islands","flag":"fo","bands":1},
 {"id_country":"IDN                             ","country":"Indonesia","flag":"id","bands":1},
 {"id_country":"IRN                             ","country":"Iran","flag":"ir","bands":1},
 {"id_country":"IRL                             ","country":"Ireland","flag":"ie","bands":1},
 {"id_country":"JAM                             ","country":"Jamaica","flag":"jm","bands":1},
 {"id_country":"JPN                             ","country":"Japan","flag":"jp","bands":1},
 {"id_country":"LTU                             ","country":"Lithuania","flag":"lt","bands":1},
 {"id_country":"MYS                             ","country":"Malaysia","flag":"my","bands":1},
 {"id_country":"MNG                             ","country":"Mongolia","flag":"mn","bands":1},
 {"id_country":"NZL                             ","country":"New Zealand","flag":"nz","bands":1},
 {"id_country":"PAN                             ","country":"Panama","flag":"pa","bands":1},
 {"id_country":"PHL                             ","country":"Philippines","flag":"ph","bands":1},
 {"id_country":"ROU                             ","country":"Romania","flag":"ro","bands":1},
 {"id_country":"SVN                             ","country":"Slovenia","flag":"si","bands":1},
 {"id_country":"ZAF                             ","country":"South Africa","flag":"za","bands":1},
 {"id_country":"ARE                             ","country":"United Arab Emirates","flag":"ae","bands":1},
]};
